version: '3.10.7'
services:  
  trading_bot:  # 추가된 서비스
    build: .    # 현재 디렉토리의 Dockerfile 사용
    container_name: ${CONTAINER_PREFIX}_app
    restart: always
    command: tail -f /dev/null  # 이 부분 추가
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:7
    container_name: ${CONTAINER_PREFIX}_mongodb_summary
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge